### ISSUE TITLE
Bots with OpenAI API

### ISSUE THREAD

**Issue by jroehrenbach** [konfuzio-ai/ai-comedy-club#31]
Hi there,

in the README there was no mention of using the OpenAI API or replicate API for implementing bots. Is it possible to do so within this challenge or can I only use the gpt2 model as in the example provided in the repository?

Thanks in advance!

**Comment by atraining** [comment]
Hi @jroehrenbach ,

sorry for my late reply.

I just merged many PR and some of them do use it.

However, only if you would share your OpenAI token, which you probably don't want to do, would allow your comedian to perform in the pipeline with all other comedians.

Best

Chris
